-- 코드를 입력하세요
SELECT A.CART_ID
FROM (SELECT CART_ID 
      FROM CART_PRODUCTS
     WHERE NAME LIKE 'Milk') AS A
LEFT JOIN CART_PRODUCTS AS B
ON A.CART_ID = B.CART_ID
WHERE B.NAME LIKE 'Yogurt'
ORDER BY A.CART_ID;