-- 코드를 입력하세요
SELECT A.CART_ID 
FROM (SELECT CART_ID, NAME AS MILK 
      FROM CART_PRODUCTS 
      WHERE NAME LIKE 'Milk') AS A
JOIN (SELECT CART_ID , NAME AS YOGURT
      FROM CART_PRODUCTS 
      WHERE NAME LIKE 'Yogurt') AS B
ON A.CART_ID = B.CART_ID
WHERE A.MILK IS NOT NULL || B.YOGURT IS NOT NULL
GROUP BY A.CART_ID
ORDER BY 1;
