-- 코드를 입력하세요
SELECT 
YEAR(B.SALES_DATE)AS YEAR, 
MONTH(B.SALES_DATE)AS MONTH, 
COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS, 
ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PUCHASED_RATIO
FROM (SELECT USER_ID, JOINED
      FROM USER_INFO       
      WHERE JOINED LIKE '2021%'
      GROUP BY USER_ID) AS A 
LEFT JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID 
WHERE B.USER_ID IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH