-- 코드를 입력하세요
SELECT A.FLAVOR  
FROM(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR)AS A
JOIN FIRST_HALF AS B
ON A.FLAVOR = B.FLAVOR 
GROUP BY FLAVOR
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
LIMIT 3;

