-- 코드를 입력하세요
SELECT B.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM  (SELECT MEMBER_ID
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNT(*) DESC
      LIMIT 1) AS A
      JOIN REST_REVIEW AS R
      ON A.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE AS B
ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;